server:
  port: 8080
spring:
  application:
    name: traffic-simulator
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:h2:file:./data/traffic-simulator
    driver-class-name: org.h2.Driver
    username: customuser
    password: Admin123!
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    schemas:
      - traffic_simulator
    baseline-on-migrate: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
